HTMLTags = [
    # https://developer.mozilla.org/en-US/docs/Web/HTML/Element
    "a","abbr","acronym","address","applet","area","article","aside","attachment","audio",
    "b","base","basefont","bdi","bdo","bgsound","big", "blink", "blockquote","body","br","button",
    "canvas","caption","center","cite","code","col","colgroup","command","content",
    "data","datalist","dd","del","details","dfn","dialog","dir","div","dl","dt",
    "element","em","embed",
    "fieldset","figcaption","figure","font","footer","form","frame","frameset",
    "h1","h2","h3","h4","h5","h6","head","header","hgroup","hr","html",
    "i","iframe","image","img","input","ins","isindex","kbd","keygen",
    "label","layer","legend","li","link","listing",
    "main","map","mark","marquee","menu","menuitem","meta","meter","multicol",
    "nav","nobr","noembed","noframes","nolayer","noscript",
    "object","ol","optgroup","option","output",
    "p","param","picture","plaintext","pre","progress",
    "q","rb","rp","rt","rtc","ruby",
    "s","samp","script","section","select","shadow","slot","small","source","spacer","span","strike","strong","style","sub","summary","sup", "svg",
    "table","tbody","td","template","textarea","tfoot","th","thead","time","title","tr","track","tt",
    "u","ul","var","video","wbr","xmp",
]

EVENTS = [
    # https://developer.mozilla.org/en-US/docs/Web/Events
    "devicelight","cached","checking","downloading","noupdate","obsolete","updateready","headphoneschange","mozinterruptbegin",
    "mozinterruptend","chargingchange","chargingtimechange","dischargingtimechange","levelchange","message",
    "mozbrowseractivitydone","mozbrowserasyncscroll","mozbrowseraudioplaybackchange","mozbrowsercaretstatechanged",
    "mozbrowserclose","mozbrowsercontextmenu","mozbrowserdocumentfirstpaint","mozbrowsererror","mozbrowserfindchange",
    "mozbrowserfirstpaint","mozbrowsericonchange","mozbrowserloadend","mozbrowserloadstart","mozbrowserlocationchange",
    "mozbrowsermanifestchange","mozbrowsermetachange","mozbrowseropensearch","mozbrowseropentab","mozbrowseropenwindow",
    "mozbrowserresize","mozbrowserscroll","mozbrowserscrollareachanged","mozbrowserscrollviewchange",
    "mozbrowsersecuritychange","mozbrowserselectionstatechanged","mozbrowsershowmodalprompt","mozbrowsertitlechange",
    "mozbrowserusernameandpasswordrequired","mozbrowservisibilitychange","message","beforecopy","beforecut",
    "beforepaste","copy","cut","paste","contactchange","error","success","loading","loadingdone","loadingerror",
    "animationend","animationiteration","animationstart","transitionend","resize","scroll","compassneedscalibration",
    "devicemotion","deviceorientation","change","abort","beforeinput","blur","click","compositionend",
    "compositionstart","compositionupdate","dblclick","error","focus","focusin","focusout","input","keydown","keyup",
    "load","mousedown","mouseenter","mouseleave","mousemove","mouseout","mouseover","mouseup","resize","scroll",
    "select","unload","wheel","statechange","encrypted","keystatuschange","message","waitingforkey","message",
    "abort","error","load","loadend","loadstart","progress","antennaavailablechange","disabled","enabled",
    "frequencychange","fullscreenchange","fullscreenerror","gamepadconnected","gamepaddisconnected",
    "DOMContentLoaded","abort","afterprint","afterscriptexecute","autocomplete","autocompleteerror",
    "beforeprint","beforescriptexecute","beforeunload","blur","cancel","canplay","canplaythrough",
    "change","click","close","connect","contextmenu","durationchange","emptied","error","focus",
    "hashchange","input","invalid","languagechange","load","loadeddata","loadedmetadata","loadend",
    "loadstart","message","offline","online","open","pagehide","pageshow","play","playing","popstate",
    "progress","readystatechange","reset","seeked","seeking","select","show","sort","stalled","storage",
    "submit","suspend","timeupdate","toggle","unload","volumechange","waiting","drag","dragend","dragenter",
    "dragexit","dragleave","dragover","dragstart","drop","abort","blocked","close","complete","error","success",
    "upgradeneeded","versionchange","message","active","addtrack","devicechange","ended","inactive","mute",
    "overconstrained","ratechange","removetrack","unmute","dataavailable","pause","resume","start","stop","abort",
    "addsourcebuffer","error","removesourcebuffer","sourceclose","sourceended","sourceopen","update","updateend",
    "updatestart","addtrack","ended","muted","overconstrained","removetrack","started","unmuted","cardstatechange",
    "icccardlockerror","close","deliveryerror","deliverysuccess","error","failed","message","open","received",
    "retrieving","sending","sent","change","visibilitychange","gotpointercapture","lostpointercapture","pointercancel",
    "pointerdown","pointerenter","pointerleave","pointermove","pointerout","pointerover","pointerup",
    "pointerlockchange","pointerlockerror","change","sessionavailable","sessionconnect","deviceproximity","userproximity",
    "push","pushsubscriptionchange","change","selectionchange","selectstart","error","message","open","activate",
    "controllerchange","error","fetch","install","message","statechange","updatefound","settingchange","error",
    "success","speakerforcedchange","DOMAttrModified","DOMCharacterDataModified","DOMNodeInserted",
    "DOMNodeInsertedIntoDocument","DOMNodeRemoved","DOMNodeRemovedFromDocument","DOMSubtreeModified","SVGAbort",
    "SVGError","SVGLoad","SVGResize","SVGScroll","SVGUnload","SVGZoom","activate","beginEvent","click","endEvent",
    "focusin","focusout","mousedown","mousemove","mouseout","mouseover","mouseup","repeatEvent","connect","data",
    "drain","error","moztimechange","touchcancel","touchend","touchmove","touchstart","currentchannelchanged",
    "currentsourcechanged","eitbroadcasted","scanningstatechanged","message","cancel","finish","audioprocess",
    "complete","ended","loaded","message","nodecreate","statechange","webglcontextcreationerror",
    "webglcontextlost","webglcontextrestored","midimessage","statechange","click","close","error","show",
    "addstream","close","datachannel","error","icecandidate","iceconnectionstatechange","icegatheringstatechange",
    "identiyresult","idpassertionerror","idpvalidationerror","isolationchange","message","negotiationneeded",
    "open","peeridentity","removestream","signalingstatechange","tonechange","close","error","message",
    "open","audioend","audiostart","boundary","end","error","mark","nomatch","pause","result","resume",
    "soundend","soundstart","speechend","speechstart","storage","incoming","addtrack","change","cuechange",
    "enter","exit","removetrack","connectioninfoupdate","statuschange","disabled","enabled",
    "peerinfoupdate","statuschange","abort","error","load","loadend","loadstart","progress",
    "readystatechange","timeout",
]

HTMLAttributes = [
    "abbr","accept_charset","accept","accesskey","action","align","alink","allowfullscreen","alt","archive",
    "aria-activedescendant","aria-atomic","aria-busy","aria-checked","aria-colcount","aria-colindex","aria-colspan",
    "aria-controls","aria-current","aria-describedby","aria-disabled","aria-dropeffect","aria-expanded","aria-flowto",
    "aria-grabbed","aria-haspopup","aria-help","aria-hidden","aria-invalid","aria-label","aria-labeledby","aria-labelledby",
    "aria-level","aria-live","aria-modal","aria-multiline","aria-multiselectable","aria-orientation","aria-owns",
    "aria-placeholder","aria-posinset","aria-pressed","aria-readonly","aria-relevant","aria-required","aria-roledescription",
    "aria-rowcount","aria-rowindex","aria-rowspan","aria-selected","aria-setsize","aria-sort","aria-valuemax",
    "aria-valuemin","aria-valuenow","aria-valuetext","async","autocomplete","autofocus","autoplay","autosave","axis",
    "background","behavior","bgcolor","bgproperties","border","bordercolor",
    "capture","cellpadding","cellspacing","char","challenge","charoff","charset","checked","cellborder","cite",
    "class","classid","clear","code","codebase","codetype","color","cols","colspan","compact","composite",
    "content","contenteditable","controls","coords","crossorigin",
    "data","datetime","declare","default","defer","dir","direction","dirname","disabled","disposition","download",
    "draggable","webkitdropzone","enctype","end","event","expanded",
    "face","focused","for","form","formaction","formenctype","formmethod","formnovalidate","formtarget","frame",
    "frameborder",
    "headers","height","hidden","high","href","hreflang","hspace","http_equiv",
    "id","incremental","indeterminate","is","ismap","itemid","itemprop","itemref","itemscope","itemtype",
    "keytype","kind",
    "label","lang","language","leftmargin","link","list","longdesc","loop","low","playcount","loopend","loopstart",
    "lowsrc",
    "manifest","marginheight","marginwidth","max","maxlength","mayscript","media","mediagroup","method","min","multiple","muted",
    "name","nohref","nonce","noresize","noshade","novalidate","nowrap",
    "object","onabort","onanimationstart","onanimationiteration","onanimationend","onautocomplete","onautocompleteerror",
    "onbeforecopy","onbeforecut","onbeforeload","onbeforepaste","onbeforeunload","onblur","oncanplay","oncanplaythrough",
    "onchange","onclick","oncontextmenu","oncopy","oncut","ondblclick","ondrag","ondragend","ondragenter","ondragleave",
    "ondragover","ondragstart","ondrop","ondurationchange","onemptied","onended","onerror","onfocus","onfocusin",
    "onfocusout","onhashchange","oninput","oninvalid","onkeydown","onkeypress","onkeyup","ongesturestart",
    "ongesturechange","ongestureend","onload","onloadeddata","onloadedmetadata","onloadstart","onmessage",
    "onmousedown","onmouseenter","onmouseleave","onmousemove","onmouseout","onmouseover","onmouseup",
    "onmousewheel","ononline","onoffline","onorientationchange","onpagehide","onpageshow","onpaste",
    "onpause","onplay","onplaying","onpopstate","onprogress","onratechange","onreset","onresize",
    "onscroll","onsearch","onseeked","onseeking","onselect","onselectstart","onselectionchange",
    "onwebkitspeechchange","onwheel","onstalled","onstorage","onsuspend","onsubmit","ontimeupdate",
    "ontouchstart","ontouchmove","ontouchend","ontouchcancel","ontransitionend","onunload","onvolumechange",
    "onwaiting","onwebkitanimationstart","onwebkitanimationiteration","onwebkitanimationend","onwebkitbeginfullscreen",
    "onwebkitendfullscreen","onwebkitfullscreenchange","onwebkitfullscreenerror","onwebkitkeyadded",
    "onwebkitkeyerror","onwebkitkeymessage","onwebkitmouseforcechanged","onwebkitmouseforcedown",
    "onwebkitmouseforceup","onwebkitmouseforcewillbegin","onwebkitneedkey","onwebkitsourceclose",
    "onwebkitsourceended","onwebkitsourceopen","onwebkittransitionend","onwebkitwillrevealbottom",
    "onwebkitwillrevealleft","onwebkitwillrevealright","onwebkitwillrevealtop","open","optimum",
    "pattern","placeholder","pluginspage","pluginurl","ping","poster","precision","preload","primary",
    "profile","progress","prompt","pseudo","readonly","rel","required","results","rev","reversed",
    "role","rows","rowspan","rules","sandbox","scheme","scope","scoped","scrollamount","scrolldelay",
    "scrolling","select","selected","shape","size","sizes","slot","sortable","sortdirection","span",
    "x-webkit-speech","x-webkit-grammar","spellcheck","src","srcset","srcdoc","srclang","standby",
    "start","step","style","subtitle","summary","tabindex","tableborder","target","text","title",
    "top","topmargin","translate","truespeed","type","uiactions","usemap","valign","value","valuetype",
    "version","vlink","vspace","webkitallowfullscreen","webkitattachmentpath","width","wrap","","autocorrect",
    "autocapitalize","onwebkitcurrentplaybacktargetiswirelesschanged","onwebkitplaybacktargetavailabilitychanged",
    "onwebkitpresentationmodechanged","x-webkit-imagemenu","webkit-playsinline","x-webkit-airplay",
    "x-webkit-wirelessvideoplaybackdisabled","x-itunes-inherit-uri-query-component",
]

NICE_VALUES = [
    "0","1","5e6","-7e6","8e-6","2e100","7500000000","4400000000","-4400000000","-7500000000","0x80000000","0xFFFFFFFF", "NaN",
    "false", "true", "null","'pink'","'ltr'","'rtl'","'auto'","'copy'","'move'","'link'","'ab'","'bg'","'en'","'no'","'open'","'controls'",
    "'\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141\\u4141'",
]

Commands=[
    'delete','insertButton','insertFieldset','insertHorizontalRule','insertIFrame','insertInputButton',
    'insertInputCheckbox','insertInputFileUpload','insertInputHidden','insertInputImage',
    'insertInputPassword','insertInputRadio','insertInputReset','insertInputSubmit','insertInputText',
    'insertMarquee','insertOrderedList','insertSelectDropdown','insertSelectListbox','insertTextArea',
    'insertUnorderedList'
]

OBJ_BLACKLIST = [
  'nodeName', 'nodeValue', 'nodeType', 'childNodes', 'location', 'name',  'opener', 'URL', 'onbeforeunload',
    'onunload','innerHTML', 'outerHTML', 'innerText', 'textContent', 'Components', 'controllers', 'lastChild',
    'previousSibling', 'previousElementSibling', 'parentNode', 'parentTextEdit', 'parentElement', 'ownerDocument',
    'document', 'cloneNode', 'open', 'close', 'print',
]

MAX_ELEM = 5

MAX_PROP = 3

MAX_ATTRS = 3

MAX_LISTENERS = 2